### ISSUE TITLE
Importing problem

### ISSUE THREAD

**Issue by dymwan** [Hanqer/deep-hough-transform#50]
Hi,
Firstly, your fantastic work is really helpful. And there is a small problem with using:

After importing the torch and deep_hough package in python, the error 
`imtens = imtens.cuda()`
`RuntimeError: CUDA error: unrecognized error code`   

occurred when I try to allocate a tensor from CPU to GPU via `tensor.cuda()`.
However, if I just simply do not import deep_hough, the error disappeared. I am sure that my software was set ok.

Here is a small demo:
![image](https://user-images.githubusercontent.com/26141745/192143166-4857e0ff-6c53-4889-93a1-dd2afd7b195c.png)

My software setup is:
pytorch 1.7 + cu11
Waiting for some suggestions sincerely.

**Comment by dymwan** [comment]
solved by using:
`import torch
import deep_hough as dh
print(dh.__file__)
torch.cuda.empty_cache()`
Add the `torch.cuda.empty_cache()`,this problem was solved, but the mechanism stays ambiguous

**Comment by Hanqer** [comment]
I think this may caused by the incompatible cuda version, you can try to compile it using cuda10.
